name: EssentialsSSH
main: com.salkcoding.essentialssshbc.EssentialsSSHBC
version: 1.1.0-SNAPSHOT
description: Essentials by Salk_Coding
api-version: 1.19
author: Salk_Coding
commands:
  home:
    description: home
  sethome:
    description: sethome
  spawn:
    description: spawn